{% set name = 'tvb-gdist' %}
{% set version = '1.5.8' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  md5: ab93aa8d8745627524debb020253bb48
  sha256: 66f63938cd2011ae5476f3e0e99ebf2a4fa7bffed3148c17e5e64c94d8c57c4e
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/t/tvb-gdist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script: python setup.py install
  skip: True  # [py>27]

requirements:
  build:
    - toolchain
    - python
    - setuptools
    - numpy
    - scipy
    - cython
  run:
    - python
    - setuptools
    - numpy
    - scipy
    - cython

test:
  imports:
    - gdist

about:
  home: https://github.com/the-virtual-brain/tvb-geodesic
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Compute geodesic distances'
  description: |
    The `gdist` module is a Cython interface to a C++ library |
    (http://code.google.com/p/geodesic/) for computing |
    geodesic distance which is the length of shortest line between two |
    vertices on a triangulated mesh in three dimensions, such that the line |
    lies on the surface.
  doc_url: http://code.google.com/p/geodesic/
  dev_url: https://github.com/the-virtual-brain/tvb-geodesic

extra:
  recipe-maintainers:
    - liadomide
