{% set name = 'tvb-gdist' %}
{% set version = '2.0.0' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  md5: 677cd29f6584a8adb0c0f5880fcf5f43
  sha256: 7b68e18c0c52b5a89d90b41737bb1c4bd661e6d4473bcbacc0cf80b4d46551ae
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/t/tvb-gdist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy
    - scipy
    - cython
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - scipy
    - cython

test:
  imports:
    - gdist

about:
  home: https://github.com/the-virtual-brain/tvb-geodesic
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Compute geodesic distances'
  description: |
    The `gdist` module is a Cython interface to a C++ library |
    (http://code.google.com/p/geodesic/) for computing |
    geodesic distance which is the length of shortest line between two |
    vertices on a triangulated mesh in three dimensions, such that the line |
    lies on the surface.
  doc_url: http://code.google.com/p/geodesic/
  dev_url: https://github.com/the-virtual-brain/tvb-geodesic

extra:
  recipe-maintainers:
    - liadomide
